# Generated by Django 3.1.7 on 2021-05-20 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        ('accounts', '0002_auto_20210520_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.rating'),
        ),
    ]
